config/routes.rb
FirstTeacher::Application.routes.draw do
  root 'pages#mission'
  match '/mission',   to: 'pages#mission',    via: 'get'
  match '/program',   to: 'pages#program',    via: 'get'
  match '/resources', to: 'pages#resources',  via: 'get'
  match '/news',      to: 'pages#news',       via: 'get'
  match '/contact',   to: 'pages#contact',    via: 'get'
  

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def mission
  end

  def program
  end

  def resources
  end

  def news
  end

  def contact
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>First Teacher</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body class="background">

      <div class="container all-content">

        <div class="header center">
          <%= image_tag "FT_logo.png", :size => "200x200", class:"logo" %>
        </div>

        <ul class="navigation">  

          <%= link_to mission_path, :class => "nav-item" do %>
            <li>
              Mission
            </li>
          <% end %>
          <%= link_to program_path, :class => "nav-item" do %>
            <li>
              Program
            </li>
          <% end %>
          <%= link_to resources_path, :class => "nav-item" do %>
            <li>
              Books & Resources
            </li>
          <% end %>
          <%= link_to news_path, :class => "nav-item" do %>
            <li>
              News & Events
            </li>
          <% end %>
          <%= link_to contact_path, :class => "nav-item" do %>
            <li>
              Contact
            </li>
          <% end %>
        </ul>

        <!-- Notes to be displayed on sucess/failure events -->
        <div class="center">
          <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>"><%= value %></div>
          <% end %>
        </div>

        <!-- Main content -->
        <div class="main-content">
          <%= yield %>
        </div>
      </div>

  </body>
</html>

app/views/pages/contact.html.erb
<div class="center">
  <h1 class="center">Contact</h1>
</div>

<div class="contact-div">
  <address>
    <strong>Dinah Shepherd</strong><br>
    <strong>Founder and Executive Director</strong><br>
    27-43 Wormwood St, Suite 110<br>
    Boston, MA 02210<br><br>
    <abbr title="Phone">Phone:</abbr> (617) 435-0042 <br>
    <abbr title="Email">Email:</abbr> <a href="mailto:#">dshepherd@bpe.org</a>
  </address>
</div>

app/views/pages/mission.html.erb
<div class="center">
  <h1 class="center">Mission</h1>
</div>

<div class="paragraph">
  <p class="excerpt">
  First Teacher, a partnership between BPE, Dudley Children Thrive, Dudley Street Neighborhood 
  Charter School and the parents of Boston, provides parents of children from birth to four with 
  the opportunity to <strong>understand and embrace their vital role in their children’s cognitive 
  development, as well as create and participate in a supportive, empowering parent cohort, 
  all under the leadership of fellow parents. </strong>
  </p>
</div>

<div class="paragraph">
  <p class="excerpt">
  First Teacher is a neighborhood initiative “of the people, by the people, for the people.” It 
  is a direct hands-on program for parents and caregivers based on the idea that if knowledge, 
  information, and effective strategies are made accessible through a non-judgmental, collaborative 
  approach, parenting practices will improve dramatically, thereby directly supporting toddlers’ 
  school readiness prospects. The long-term goal of First Teacher is that children enter K1 at or 
  above grade-level in literacy skills and general school readiness.
  </p>
</div>

app/views/pages/news.html.erb
<div class="center">
  <h1 class="center">News</h1>
  <span class="center">
    <strong>Coming Soon! </strong>
  </span>
</div>

app/views/pages/program.html.erb
<div class="center">
  <h1 class="center">Program</h1>
</div>

<div class="paragraph">
  <p class="excerpt">
    First Teacher is a home and neighborhood-based school readiness program in which high-achieving parents from the community partner with cohorts of parents of children 0-4 in the role of mentor and teacher and using the surrounding environment as an organic classroom. The three areas of focus for learning and practice in First Teacher are:
  </p>

  <ul>
    <li>
      Early language acquisition and literacy;
    </li>
    <li>
      Executive functioning; and
    </li>
    <li>
      General school readiness
    </li>
  </ul>

  <p class="excerpt">
    These services are offered through:
  </p>

  <ul>
    <li>
      high-quality, literacy-rich, intellectually stimulating, monthly workshops located at Dudley Street Neighborhood Charter School or Dudley Street Neighborhood Initiative
    </li>
    <li>
      monthly parent mentor home visits to provide guidance and support the program’s three areas of focus;
    </li>
    <li>
      optional monthly activities (field trips, potlucks, movie night, etc.) that highlight the pedagogical practices of First Teacher.
    </li>
  </ul>

</div>

app/views/pages/resources.html.erb
<div class="center">
  <h1 class="center">Resources</h1>
  <span class="center">
    <strong>Coming Soon! </strong>
  </span>
</div>

app/views/partials/_navbar.html.erb
<!-- Navigation bar. -->

<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      Logo goes here.
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", root_path %></li>
          <li><%= link_to "Sign in", root_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>